### ISSUE TITLE
alpha always 0

### ISSUE THREAD

**Issue by marctaule** [Qiu-Jun/color-gradient-picker-vue3#5]
Hi Qiu-Jun!
Thank you for converting this plugin to Vue 3 :) 
I'm having issues with the color picker. If my initial color is, for example:
`{
  red: 0,
  green: 0,
  blue: 0,
  alpha: 0.3
}`
When I click on any other color, the alpha value doesn't stay and always sets to 0.
Do you know why this might be happening to me?
Thanks!

**Comment by Qiu-Jun** [comment]
> Hi Qiu-Jun! Thank you for converting this plugin to Vue 3 :) I'm having issues with the color picker. If my initial color is, for example: `{ red: 0, green: 0, blue: 0, alpha: 0.3 }` When I click on any other color, the alpha value doesn't stay and always sets to 0. Do you know why this might be happening to me? ThanksBe


> Hi Qiu-Jun! Thank you for converting this plugin to Vue 3 :) I'm having issues with the color picker. If my initial color is, for example: `{ red: 0, green: 0, blue: 0, alpha: 0.3 }` When I click on any other color, the alpha value doesn't stay and always sets to 0. Do you know why this might be happening to me? Thanks!

Because alpha will reset when it changes.I has optimizing the component.
I will solve the issue in next version soon.

**Comment by Qiu-Jun** [comment]
> Hi Qiu-Jun! Thank you for converting this plugin to Vue 3 :) I'm having issues with the color picker. If my initial color is, for example: `{ red: 0, green: 0, blue: 0, alpha: 0.3 }` When I click on any other color, the alpha value doesn't stay and always sets to 0. Do you know why this might be happening to me? Thanks!

The new version will be finished in a few days

**Comment by marctaule** [comment]
Oh great! I'll wait for your update then :) Thanks!

**Comment by Qiu-Jun** [comment]
> Oh great! I'll wait for your update then :) Thanks!

hi, marctaule.i had released version 2.x.You try again. if you have any other questions ，feedback to me here

**Comment by Qiu-Jun** [comment]
I haven't updated the usage docs.
`<div>
      <ColorPicker :color="color" @change="onChange"  />
    </div>
    <div>
      <ColorPicker is-gradient @change="onChange"  />
 </div>`

you can get color in `@change="onChange"`

**Comment by marctaule** [comment]
Hi @Qiu-Jun !

I've updated to 2.0.1 but I think it doesn't work at all. 

Now the opacity doesn't reset when I change the colors. That's fine :)

But I have some errors like: 

This is my code:
`<ColorPicker
                v-if="isShadowColorPicker"
                :color="shadowSelected.color"
               @change="onShadowColorPickerHandler" />`

1) I can not get the color on "onChange" like in the other version. 

2) And in this new version, I see the buttons "Confirm" and "Close". In the other version, I didn't see these buttons... If I use onChange, I don't need these buttons. 

Maybe you could create some boolean props: confirmButton and cancelButton. Of if cancelText/confirmText is empty don't show the buttons. It's just an idea.

3) and the last suggestion: maybe for colors and gradient, could use just css text? 
For color is easy to transform { red: 255, green: 0, blue: 0, alpha: 1 } to rgba, but for gradient is more complicated. 
I think it could be better if the user could use just css for example: linear-gradient(109.6deg, rgb(218, 185, 252) 11.2%, rgb(125, 89, 252) 91.1%). I don't know how difficult this could be.

Thanks for you great work :)

**Comment by Qiu-Jun** [comment]
> Hi @Qiu-Jun !
> 
> I've updated to 2.0.1 but I think it doesn't work at all.
> 
> Now the opacity doesn't reset when I change the colors. That's fine :)
> 
> But I have some errors like:
> 
> This is my code: `<ColorPicker v-if="isShadowColorPicker" :color="shadowSelected.color" @change="onShadowColorPickerHandler" />`
> 
> 1. I can not get the color on "onChange" like in the other version.
> 2. And in this new version, I see the buttons "Confirm" and "Close". In the other version, I didn't see these buttons... If I use onChange, I don't need these buttons.
> 
> Maybe you could create some boolean props: confirmButton and cancelButton. Of if cancelText/confirmText is empty don't show the buttons. It's just an idea.
> 
> 3. and the last suggestion: maybe for “color” prop, could use just css text?
>    For solid color is easy to transform { red: 255, green: 0, blue: 0, alpha: 1 } to rgba, but for gradient is more complicated.
>    I think it could be better if the user could use just css for example: linear-gradient(109.6deg, rgb(218, 185, 252) 11.2%, rgb(125, 89, 252) 91.1%). I don't know how difficult this could be.
> 
> Thanks for you great work :)

The button is used to solve the problem of updating frequently, i can resve it with other solutions.
But gradient can't use just css text.Because this lib is mainly used for  [vue-fabric-editor](https://github.com/nihaojob/vue-fabric-editor).It need gradient point to work for `fabric`.

**Comment by Qiu-Jun** [comment]
> frequently

I had released version 2.0.2.You can install it to try.It's don't show the footer button, when showBtn isn't `true`.
If you don't need the button.You'd better use `debounce or throttle` to optimize `@change Event`, Both `click` and `mousemove` execute `updateColor`, then it will handle emit to prarent component.

**Comment by marctaule** [comment]
Hi @Qiu-Jun ! 
I've just test your updates and almost everything works fine :)

I tell you what I've found:

**1) Solid color:** everything is perfect!

**2) Gradient:**
- When I add colors, I can not delete them
- I can not change the color of the colors of the gradient. I attach you some screenshots. You will see that the first color would be green. If I select green, for example, and I add another color, then this color is green, but then I can not change this color again. You know what I meant?

[Image 1](https://ibb.co/WV4DGsv)
[Image 2](https://ibb.co/MhQdQz6)

I didn't know vue-fabric-editor. It's amazing! :)

**Comment by Qiu-Jun** [comment]
> Hi @Qiu-Jun ! I've just test your updates and almost everything works fine :)
> 
> I tell you what I've found:
> 
> **1) Solid color:** everything is perfect!
> 
> **2) Gradient:**
> 
> * When I add colors, I can not delete them
> * I can not change the color of the colors of the gradient. I attach you some screenshots. You will see that the first color would be green. If I select green, for example, and I add another color, then this color is green, but then I can not change this color again. You know what I meant?
> 
> [Image 1](https://ibb.co/WV4DGsv) [Image 2](https://ibb.co/MhQdQz6)
> 
> I didn't know vue-fabric-editor. It's amazing! :)

Do you mean you want to change the gradient color of the selected point?

**Comment by Qiu-Jun** [comment]
> Hi @Qiu-Jun ! I've just test your updates and almost everything works fine :)
> 
> I tell you what I've found:
> 
> **1) Solid color:** everything is perfect!
> 
> **2) Gradient:**
> 
> * When I add colors, I can not delete them
> * I can not change the color of the colors of the gradient. I attach you some screenshots. You will see that the first color would be green. If I select green, for example, and I add another color, then this color is green, but then I can not change this color again. You know what I meant?
> 
> [Image 1](https://ibb.co/WV4DGsv) [Image 2](https://ibb.co/MhQdQz6)
> 
> I didn't know vue-fabric-editor. It's amazing! :)

you can delete the point by dbclick it.

**Comment by Qiu-Jun** [comment]
> > Hi @Qiu-Jun ! I've just test your updates and almost everything works fine :)
> > I tell you what I've found:
> > **1) Solid color:** everything is perfect!
> > **2) Gradient:**
> > 
> > * When I add colors, I can not delete them
> > * I can not change the color of the colors of the gradient. I attach you some screenshots. You will see that the first color would be green. If I select green, for example, and I add another color, then this color is green, but then I can not change this color again. You know what I meant?
> > 
> > [Image 1](https://ibb.co/WV4DGsv) [Image 2](https://ibb.co/MhQdQz6)
> > I didn't know vue-fabric-editor. It's amazing! :)
> 

> + You can delete the point by dbclick it.
> + Do you mean you want to change the gradient color of the selected point?

**Comment by Qiu-Jun** [comment]
> > You can delete the point by dbclick it.
> 
> Ok! Perfect! It works :) I think in the previous versions you could delete gradient points with the Delete key, couldn't you?
> 
> > Do you mean you want to change the gradient color of the selected point?
> 
> Yes. I can not change the color of a selected point of the gradient. I think in the previous version, it works.

it can't woks in the previous version.I really didn't handle it well. I will fix it soon

**Comment by marctaule** [comment]
"oh! I thought so, sorry for the mistake. I could have sworn it was working. 
No worries, I'll wait for you to fix it, I'm interested in the gradient selector working perfectly :)
Thanks @Qiu-Jun !

**Comment by Qiu-Jun** [comment]
> "oh! I thought so, sorry for the mistake. I could have sworn it was working. No worries, I'll wait for you to fix it, I'm interested in the gradient selector working perfectly :) Thanks @Qiu-Jun !

I had fixed it and release new version 2.0.4.You upgrade and try it again.
I want it to be perfect， too.

**Comment by marctaule** [comment]
Hi @Qiu-Jun ! 

Now it works perfect! 

If you allow me I make you a suggestion to improve the ux:

Allow users to remove the selected points in gradient, instead of double click. 
Sometimes it's difficult to click the point, because the point moves to left. 
It works rare now. It's difficult to remove a point now.

And I found an error at the documentation. 
The prop/attribute "gradient", it doesn't work for gradients. 
You have to use "color" like in solid color:

```
<ColorPicker
        :color="color"
        cancel-text="cancel"
        cancel-color="red"
        @change="onChange"
      />
```
     
This:  
```
<ColorPicker
     :is-gradient="color"
     :color="color"
     cancel-text="cancel"
     cancel-color="red"
     @change="onChange"
/>
```
instead of:
```
<ColorPicker
     :is-gradient="color"
     :gradient="color"
     cancel-text="cancel"
     cancel-color="red"
     @change="onChange"
/>
```

**Comment by Qiu-Jun** [comment]
> Hi @Qiu-Jun !
> 
> Now it works perfect!
> 
> Just a thing:
> 
> If I pass a gradient to **:gradient** attribute the ColorPicker doesn't apply this gradient. If I pass **:color** instead of **:gradient**, it applies the gradient, but the selected point is always red. I think the selected should be green in this case. It's difficult to explain for me... I attach you picture.
> 
> [Image](https://pasteboard.co/K2zDUFS5Zpc5.png)
> 
> And if you allow me I make you a suggestion to improve the ux: Allow users to remove the selected points in gradient, instead of double click. Sometimes it's difficult to click the point, because the point moves to left. It works rare now. It's difficult to remove a point now.

oh, i'm so sorry that i forget to update the documents.
I had release `2.0.5` and the document, you upgrade and try again.
Now solid and gradient  are in color attributes.
for example, solid color like:
`<ColorPicker :color="color" show-btn @change="onChange" />`
`const color = {
  red: 0,
  green: 8,
  blue: 255,
  alpha: 1,
}
`
and graditent like:
`<ColorPicker is-gradient :color="gradientColort" @change="onChange" />`
`const gradientColort = {
  type: 'linear',
  degree: 0,
  points: [
    {
      id: '81bcb3a0-00b9-4a26-bfc7-2b261722de02',
      left: 0,
      red: 0,
      green: 0,
      blue: 0,
      alpha: 1,
    },

    {
      id: 'a5d144fb-9ab5-40b3-9beb-e79161c5f546',
      red: 0,
      green: 153,
      blue: 255,
      alpha: 1,
      left: 32.25806451612903,
    },
    {
      id: 'b1bc25ad-7273-4bd8-ad22-d5d11cab0f55',
      red: 0,
      green: 153,
      blue: 255,
      alpha: 1,
      left: 68.95161290322581,
    },
    {
      id: 'd6c7ccb8-b1c4-4470-8b73-ee0b56739421',
      left: 97.1774193548387,
      red: 255,
      green: 0,
      blue: 63,
      alpha: 1,
    },
  ],
}`
 you can see the path `lib/src/App.vue`.


And Thank you very much for your suggestion about ux.
You are right. Do you think how to delete is prefect!
